#!/bin/bash
echo "To cleanup execute the PICOS/Apps/cleanup script in this directory,"
echo "such that this directory is current when the script is run, for example:"
echo "../../PICOS/PICOS/Apps/cleanup"
